2021/03/10 13:22:45 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/info
2021/03/10 13:22:45 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
[2021-03-10T13:22:46.924160] Entering context manager injector.
[context_manager_injector.py] Command line Options: Namespace(inject=['ProjectPythonPath:context_managers.ProjectPythonPath', 'RunHistory:context_managers.RunHistory', 'TrackUserError:context_managers.TrackUserError'], invocation=['trainCovid19Dataset.py', '--C', '100', '--max_iter', '25'])
Script type = None
Starting the daemon thread to refresh tokens in background for process with pid = 117
[2021-03-10T13:22:48.747114] Entering Run History Context Manager.
[2021-03-10T13:22:49.554247] Current directory: /mnt/batch/tasks/shared/LS_root/jobs/quick-starts-ws-140146/azureml/covid19hyperdrexperiment_1615381578337/mounts/workspaceblobstore/azureml/Covid19HyperDrExperiment_1615381578337
[2021-03-10T13:22:49.554641] Preparing to call script [trainCovid19Dataset.py] with arguments:['--C', '100', '--max_iter', '25']
[2021-03-10T13:22:49.554755] After variable expansion, calling script [trainCovid19Dataset.py] with arguments:['--C', '100', '--max_iter', '25']

Starting the daemon thread to refresh tokens in background for process with pid = 117


[2021-03-10T13:22:50.083854] The experiment failed. Finalizing run...
Cleaning up all outstanding Run operations, waiting 900.0 seconds
1 items cleaning up...
Cleanup took 0.05852317810058594 seconds
Starting the daemon thread to refresh tokens in background for process with pid = 117
Traceback (most recent call last):
  File "trainCovid19Dataset.py", line 18, in <module>
    import kaggle
ModuleNotFoundError: No module named 'kaggle'

[2021-03-10T13:22:50.418951] Finished context manager injector with Exception.
2021/03/10 13:22:50 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 1
FilteredData: 0.
2021/03/10 13:22:51 Could not parse control script error at path: /mnt/batch/tasks/workitems/0be768d4-c9df-48ba-920f-93013f48b8cf/job-1/covid19hyperdrexperi_58d1df14-0df4-4666-9ae9-313a7c60e368/wd/runTaskLetTask_error.json because: File /mnt/batch/tasks/workitems/0be768d4-c9df-48ba-920f-93013f48b8cf/job-1/covid19hyperdrexperi_58d1df14-0df4-4666-9ae9-313a7c60e368/wd/runTaskLetTask_error.json doesn't exist, continuing without
2021/03/10 13:22:51 Failed to run the wrapper cmd with err: exit status 1
2021/03/10 13:22:51 Attempt 1 of http call to http://10.0.0.4:16384/sendlogstoartifacts/status
2021/03/10 13:22:51 mpirun version string: {
Intel(R) MPI Library for Linux* OS, Version 2018 Update 3 Build 20180411 (id: 18329)
Copyright 2003-2018 Intel Corporation.
}
2021/03/10 13:22:51 MPI publisher: intel ; version: 2018
2021/03/10 13:22:51 Not exporting to RunHistory as the exporter is either stopped or there is no data.
Stopped: false
OriginalData: 2
FilteredData: 0.
2021/03/10 13:22:51 Process Exiting with Code:  1
