2021-03-23 13:25:32.987 - INFO - 30600 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-23 13:25:33.006 - INFO - 30600 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-23 13:25:33.011 - INFO - 30600 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-23 13:25:33.402 - INFO - 30600 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=391.27[ms]
2021-03-23 13:25:33.474 - INFO - 30600 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=468.4[ms]
2021-03-23 13:25:33.475 - INFO - 30600 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-23 13:25:35.530 - INFO - 30600 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-23 13:25:36.774 - INFO - 30600 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-23 13:25:36.774 - INFO - 30600 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-23 13:25:38.001 - INFO - 30600 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=4525.7[ms]
2021-03-23 13:25:38.051 - INFO - 30600 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=5064.12[ms]
2021-03-23 13:25:41.440 - INFO - 30600 - azureml.train.automl.run._log_activity:55 - ActivityStarted: RegisterModel
2021-03-23 13:25:41.462 - INFO - 30600 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-23 13:25:41.599 - INFO - 30600 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=136.73[ms]
2021-03-23 13:25:42.449 - INFO - 30600 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=1009.54[ms]
2021-03-23 20:22:40.929 - INFO - 19448 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-23 20:22:41.073 - INFO - 19448 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-23 20:22:41.095 - INFO - 19448 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-23 20:22:41.234 - INFO - 19448 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=139.49[ms]
2021-03-23 20:22:41.294 - INFO - 19448 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=221.18[ms]
2021-03-23 20:22:41.304 - INFO - 19448 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-23 20:22:43.182 - INFO - 19448 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-23 20:22:44.290 - INFO - 19448 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-23 20:22:44.309 - INFO - 19448 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-23 20:22:45.529 - INFO - 19448 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=4225.27[ms]
2021-03-23 20:22:45.581 - INFO - 19448 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=4652.58[ms]
2021-03-23 20:22:49.447 - INFO - 19448 - azureml.train.automl.run._log_activity:55 - ActivityStarted: RegisterModel
2021-03-23 20:22:49.459 - INFO - 19448 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-23 20:22:49.618 - INFO - 19448 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=159.0[ms]
2021-03-23 20:22:50.182 - INFO - 19448 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=734.9[ms]
2021-03-26 10:55:36.380 - INFO - 29166 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-26 10:55:36.476 - INFO - 29166 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-26 10:55:36.488 - INFO - 29166 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-26 10:55:36.571 - INFO - 29166 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-26 10:55:37.330 - CRITICAL - 29166 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 826, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 10:55:37.346 - INFO - 29166 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=774.62[ms]
2021-03-26 10:55:37.355 - CRITICAL - 29166 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 785, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 826, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 10:55:37.363 - INFO - 29166 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=874.35[ms]
2021-03-26 10:55:37.373 - CRITICAL - 29166 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 785, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 826, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 10:55:37.393 - INFO - 29166 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=916.17[ms]
2021-03-26 10:55:37.393 - CRITICAL - 29166 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 698, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 785, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 826, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 10:55:37.393 - INFO - 29166 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1012.91[ms]
2021-03-26 12:10:12.192 - INFO - 5591 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 12:10:12.238 - INFO - 5591 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 12:10:12.255 - INFO - 5591 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 12:10:12.315 - INFO - 5591 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 12:10:12.529 - CRITICAL - 5591 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:10:12.530 - INFO - 5591 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=214.43[ms]
2021-03-26 12:10:12.530 - CRITICAL - 5591 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:10:12.531 - INFO - 5591 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=275.23[ms]
2021-03-26 12:10:12.531 - CRITICAL - 5591 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:10:12.531 - INFO - 5591 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=293.57[ms]
2021-03-26 12:10:12.532 - CRITICAL - 5591 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 695, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:10:12.532 - INFO - 5591 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=339.73[ms]
2021-03-26 12:45:17.863 - INFO - 18856 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 12:45:17.888 - INFO - 18856 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 12:45:17.901 - INFO - 18856 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 12:45:18.079 - INFO - 18856 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 12:45:20.569 - CRITICAL - 18856 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:45:20.570 - INFO - 18856 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=2490.26[ms]
2021-03-26 12:45:20.571 - CRITICAL - 18856 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:45:20.571 - INFO - 18856 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=2670.05[ms]
2021-03-26 12:45:20.571 - CRITICAL - 18856 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:45:20.572 - INFO - 18856 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2683.91[ms]
2021-03-26 12:45:20.572 - CRITICAL - 18856 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 695, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 625, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 782, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 823, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-03-26 12:45:20.572 - INFO - 18856 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=2709.42[ms]
2021-03-26 14:15:27.229 - INFO - 21913 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 14:15:27.297 - INFO - 21913 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 14:15:27.307 - INFO - 21913 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 14:15:27.439 - INFO - 21913 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=132.59[ms]
2021-03-26 14:15:27.439 - INFO - 21913 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=142.69[ms]
2021-03-26 14:15:27.449 - INFO - 21913 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-26 14:15:42.477 - INFO - 21913 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-26 14:15:46.197 - INFO - 21913 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-26 14:15:46.197 - INFO - 21913 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-26 14:15:49.178 - INFO - 21913 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=21729.12[ms]
2021-03-26 14:15:49.179 - INFO - 21913 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=21949.57[ms]
2021-03-26 14:15:54.566 - INFO - 21913 - azureml.train.automl.run._log_activity:54 - ActivityStarted: RegisterModel
2021-03-26 14:15:54.576 - INFO - 21913 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 14:15:54.701 - INFO - 21913 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=125.1[ms]
2021-03-26 14:15:55.331 - INFO - 21913 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=765.2[ms]
2021-03-26 23:23:59.027 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 23:23:59.173 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-03-26 23:23:59.193 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 23:23:59.349 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=156.13[ms]
2021-03-26 23:23:59.349 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=175.65[ms]
2021-03-26 23:23:59.355 - INFO - 23449 - azureml.train.automl._model_download_utilities._log_activity:54 - ActivityStarted: DownloadModel
2021-03-26 23:24:00.662 - INFO - 23449 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-26 23:24:01.398 - INFO - 23449 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-26 23:24:01.398 - INFO - 23449 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-26 23:24:01.931 - INFO - 23449 - azureml.train.automl._model_download_utilities._log_activity:92 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=2575.68[ms]
2021-03-26 23:24:01.931 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=2903.62[ms]
2021-03-26 23:24:05.279 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: RegisterModel
2021-03-26 23:24:05.288 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 23:24:05.445 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=156.11[ms]
2021-03-26 23:24:07.017 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=1738.25[ms]
2021-03-26 23:48:07.793 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: RegisterModel
2021-03-26 23:48:07.838 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-26 23:48:07.978 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=140.48[ms]
2021-03-26 23:48:08.690 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=896.48[ms]
2021-03-27 00:23:57.908 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: RegisterModel
2021-03-27 00:23:57.911 - INFO - 23449 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-03-27 00:23:58.040 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=128.71[ms]
2021-03-27 00:23:59.451 - INFO - 23449 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=RegisterModel, HowEnded=Success, Duration=1542.94[ms]
